---
- hosts: linuxenv
  tasks:
    - name: update the system
      yum:
        name: "*"
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status
    - name: Reboot when Packages were updated
      reboot:
      when: yum_update_status.changed

